Make debugging unmatched requests easier
ChorusOne/rvcr pull request #14
Opened 2024-01-13 01:32 UTC by amosjyng

Hey, thanks for the great library! I added some print statements in my fork because I found it cumbersome to debug failing tests. I can hide this logic behind a flag or something if you're interested in merging this PR

2024-01-16 22:44 UTC, mksh requested changes
Hello! Thank you for the contribution. This idea looks good overall, but PR needs some changes to get it through

- please make diff printing functionality to be optional, with `VCRMiddleware` method named like `with_rich_diff` turning it on
- please use `tracing::info!` macro to print diff instead of `eprintln!()`, so output can be managed by `RUST_LOG` environment configs
- please add integration test that has unmatched request sent, and verifies the diff is printed in correct form (can use `tracing-test` https://github.com/dbrgn/tracing-test library to capture what is being printed in tests).

Thanks in advance!

2024-01-24 04:37 UTC, amosjyng commented
Thanks for the review! I'm currently trying to make a deadline, but I'll give this a pass in a few weeks if that's ok :)

2024-01-25 02:16 UTC, mksh commented
Yeah that's fine for sure, follow up on your discretion I am always open for review!

2024-02-27 06:59 UTC, amosjyng commented
Ok, I've made an initial pass at implementing the suggestions! Some notes:

- I changed the implementation of `Middleware.handle` to return a `reqwest_middleware::Error::Middleware` instead of panicking, because it seems hard to test for emitted logs after panicking. In particular, [catch-unwind](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html) does not take async functions. This would also allow for usage of this library in non-test contexts.
- Due to the above, I added `anyhow` as a crate dependency because [request-middleware v0.1.6](https://crates.io/crates/reqwest-middleware/0.1.6/dependencies) depends on `anyhow` already, and [`reqwest_middleware::Error`](https://docs.rs/reqwest-middleware/0.1.6/reqwest_middleware/enum.Error.html) expects an `anyhow::Error`
- While `tracing_test::traced_test` successfully prints out the entire debug output, it appears to only save the first line when it comes time to call `logs_contain`. As such, I split each line of output when emitting the trace, and recombine them at the end of the test.

Let me know what you think :)

2024-03-05 22:08 UTC, mksh approved these changes
LGTM

2024-03-05 22:09 UTC, merged

2024-03-05 22:26 UTC, mksh commented
Released 0.2.1 version with changes: https://crates.io/crates/rvcr/0.2.1

2024-03-05 23:09 UTC, amosjyng commented
Nice, thank you!